version: "3"
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: development
      MYSQL_USER: 123
      MYSQL_PASSWORD: 123
  app:
    image: xlayer.co.za:5000/fnbvendorportal/app:1.1.0
    ports:
      - "1337:1337"
    volumes:
      - .:/code
    environment:
      - NODE_ENV=staging
      - DATABASE_HOST=db
      - DATABASE_NAME=development
      - DATABASE_PASSWORD=123
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=123
      - HOST=localhost
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    command: sh -c "/wait && yarn start"
